// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package serve

import (
	"svix-poc/app/router"
	"svix-poc/app/router/api"
	"svix-poc/app/router/grpc"
	"svix-poc/app/router/repo"
	"svix-poc/app/router/topic"
	"svix-poc/app/webhook"
	"svix-poc/app/webhook/api"
	"svix-poc/app/webhook/grpc"
	"svix-poc/app/webhook/svix"
	"svix-poc/app/webhook/topic"
	"svix-poc/lib/app"
)

// Injectors from wire.go:

func RouterApp() app.Actor {
	repository := repo.Provide()
	dependencies := router.Dependencies{
		Repository: repository,
	}
	adapter := routerapi.Provide(dependencies)
	serverAdapter := routergrpc.Provide(dependencies)
	routertopicAdapter := routertopic.Provide(dependencies)
	actor := NewRouterApp(adapter, serverAdapter, routertopicAdapter, dependencies)
	return actor
}

func WebHookApp() app.Actor {
	svixClient := svixclient.Provide()
	dependencies := webhook.Dependencies{
		SvixClient: svixClient,
	}
	adapter := webhookapi.Provide(dependencies)
	serverAdapter := webhookgrpc.Provide(dependencies)
	webhooktopicAdapter := webhooktopic.Provide(dependencies)
	actor := NewWebHookApp(adapter, serverAdapter, webhooktopicAdapter, dependencies)
	return actor
}
