// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: app/webhook/grpc/v1/webhook.proto

package webhooksv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAppsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAppsRequest) Reset() {
	*x = CreateAppsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_webhook_grpc_v1_webhook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppsRequest) ProtoMessage() {}

func (x *CreateAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_webhook_grpc_v1_webhook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppsRequest.ProtoReflect.Descriptor instead.
func (*CreateAppsRequest) Descriptor() ([]byte, []int) {
	return file_app_webhook_grpc_v1_webhook_proto_rawDescGZIP(), []int{0}
}

type CreateAppsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAppsResponse) Reset() {
	*x = CreateAppsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_webhook_grpc_v1_webhook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppsResponse) ProtoMessage() {}

func (x *CreateAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_webhook_grpc_v1_webhook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppsResponse.ProtoReflect.Descriptor instead.
func (*CreateAppsResponse) Descriptor() ([]byte, []int) {
	return file_app_webhook_grpc_v1_webhook_proto_rawDescGZIP(), []int{1}
}

var File_app_webhook_grpc_v1_webhook_proto protoreflect.FileDescriptor

var file_app_webhook_grpc_v1_webhook_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x70, 0x2f, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x76, 0x31,
	0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x70, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x5f, 0x0a, 0x0e, 0x57,
	0x65, 0x62, 0x48, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x73, 0x12, 0x1e, 0x2e, 0x77, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x70, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x77, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x70, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29, 0x5a, 0x27,
	0x73, 0x76, 0x69, 0x78, 0x2d, 0x70, 0x6f, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x77, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x77, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_webhook_grpc_v1_webhook_proto_rawDescOnce sync.Once
	file_app_webhook_grpc_v1_webhook_proto_rawDescData = file_app_webhook_grpc_v1_webhook_proto_rawDesc
)

func file_app_webhook_grpc_v1_webhook_proto_rawDescGZIP() []byte {
	file_app_webhook_grpc_v1_webhook_proto_rawDescOnce.Do(func() {
		file_app_webhook_grpc_v1_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_webhook_grpc_v1_webhook_proto_rawDescData)
	})
	return file_app_webhook_grpc_v1_webhook_proto_rawDescData
}

var file_app_webhook_grpc_v1_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_webhook_grpc_v1_webhook_proto_goTypes = []interface{}{
	(*CreateAppsRequest)(nil),  // 0: webhooks.v1.CreateAppsRequest
	(*CreateAppsResponse)(nil), // 1: webhooks.v1.CreateAppsResponse
}
var file_app_webhook_grpc_v1_webhook_proto_depIdxs = []int32{
	0, // 0: webhooks.v1.WebHookService.CreateApps:input_type -> webhooks.v1.CreateAppsRequest
	1, // 1: webhooks.v1.WebHookService.CreateApps:output_type -> webhooks.v1.CreateAppsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_webhook_grpc_v1_webhook_proto_init() }
func file_app_webhook_grpc_v1_webhook_proto_init() {
	if File_app_webhook_grpc_v1_webhook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_webhook_grpc_v1_webhook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_webhook_grpc_v1_webhook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_webhook_grpc_v1_webhook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_webhook_grpc_v1_webhook_proto_goTypes,
		DependencyIndexes: file_app_webhook_grpc_v1_webhook_proto_depIdxs,
		MessageInfos:      file_app_webhook_grpc_v1_webhook_proto_msgTypes,
	}.Build()
	File_app_webhook_grpc_v1_webhook_proto = out.File
	file_app_webhook_grpc_v1_webhook_proto_rawDesc = nil
	file_app_webhook_grpc_v1_webhook_proto_goTypes = nil
	file_app_webhook_grpc_v1_webhook_proto_depIdxs = nil
}
